### PR TITLE
Add support for mutiple values per timestamp with ids

### PR DESCRIPTION
**Pull request by bmo-at**
As explained in #2, I'd like to contribute my changes back to you.
Shouldn't be too many changes, but a thorough review is always welcome :)

### CODE REVIEW

**Comment by rvdwijngaard** [comment]
Hi @bmo-at thanks for your PR; I think some additional changes are required to keep this plugin compatible with the current version. I have some ideas how this can be done and I will try that out. Do you have experience with multiple API versions with grpc based services? 

The idea I have is roughly this: 
1. put the current proto file in a v1 folder
2. create a new v2 folder with the modified version of the api 
3. enhance the client package
  a. add a factory -> selects the appropriate implementation based on reflection 
  b. v1 adapter which translate v1 request / responses to v2 

Note: this solution expects v2 clients to support [grpc reflection ](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto)

An alternative approach is to provide the plugin configuration with a backend API version. Any ideas?

**Comment by bmo-at** [comment]
I unfortunately do not have a lot of experience with grpc; let alone managing multiple API versions with services based on grpc. But there's nothing that can't be learned, right?

I'm definitely with you on splitting this in a v1/v2 API situation where the grpc client selects the version it prefers.
This seems like a good way to prevent breaking all the existing implementations of clients that expect the v1 proto file.

Can you go into more detail on how you'd enhance the client package?
Specifically, how do you suggest a client makes the decision to go for the v2 API, what data do they receive from the reflection call?

The alternative approach with the configuration option seems fairly trivial and is probably easiest to implement but seems undesirable due to the necessary user intervention.

**Comment by rvdwijngaard** [comment]
Short update: I'll see if I can make a PR of the proposed change. Might take a couple of days.

**Comment by rvdwijngaard** [comment]
It takes a bit longer than expected because of some other deadlines.

**Comment by rvdwijngaard** [comment]
I close this PR since proposed changes are now in the main branch

**Pull request closed without merging**
